### ISSUE TITLE
Interface issues

### ISSUE THREAD

**Issue by dnbard** [dnbard/brackets-documents-toolbar#39]
@iahvector said: I did, drag and drop works, but now it looks like this
![screenshot from 2014-12-10 14 34 26](https://cloud.githubusercontent.com/assets/1708084/5376076/13cdef1c-807a-11e4-9f00-594eb0402853.png)

**Comment by kmoskwiak** [comment]
same problem. I have linux too.
Also menu on the left is missing (no settings and closing button).

I'm after fresh install of linux and brackets. I haven't experienced that before
![screen](https://cloud.githubusercontent.com/assets/5294519/5603952/070dd382-939e-11e4-90c1-64d54e136d53.jpg)

**Comment by dnbard** [comment]
Menu toolbar are handled differently on Linux.
If you manage to find solution to this issue then please make a pull request with it.

**Comment by arjunrp** [comment]
@kmoskwiak, @iahvector   You can install another extension named 'Upper Titlebar' in linux to solve this issue.

**Comment by iahvector** [comment]
@arjunrp installing upper titlebar was not useful
