### ISSUE TITLE
Tab Color Rules

### ISSUE THREAD

**Issue by johnhidey** [dnbard/brackets-documents-toolbar#43]
The setting of a tab color for folders like templates/*.* doesn't appear to work.  Not sure if by design but would be nice.  I usually like to be able to look at the color of the tab to give me an indication of where that file came from.  

Sample rules maybe something like this.

* js/*.* (blue background, white foreground)
* templates/*.* (orange background, white foreground)
* viewmodels/*.* (green background, white foreground)

**Comment by dnbard** [comment]
Hello, I'm adding the ability to create custom rules with the RegExp:
![example](http://content.screencast.com/users/dnbard/folders/Jing/media/a52c39c8-a457-4985-aac8-eb6d492c8bf0/2015-02-06_1357.png)

Your sample rules will be changed to this:
* /js\/./
* /templates\/./
* /viewmodels\/./

**Comment by johnhidey** [comment]
Works like a champ.  Thanks
