### ISSUE TITLE
Toggle Close-Button / Reopen closed Tabs / Save Session on Exit

### ISSUE THREAD

**Issue by inovek** [dnbard/brackets-documents-toolbar#49]
Some suggestions:

1. Toggle Close-Button in Settings
Please allow an option to toggle the Close-Button on Tabs on and off.
I often work with shortnames, and when I click to the tab it often closing, because I clicked on the area of the Close-Button. So long the middle-click to close is avaible, I'm fine.

2. Hotkey to open closed Tabs
You know this feature already from browsers or Sublime. When you click CMD-Shift-T (or for Win Ctrl-Shift-T), then the closed Tab/File will reopen again.

3. Save Session (not files on exit)
I don't know if such a idea is for a tabbing plugin, but in Sublime it is nice that you can close the application with unsaved files, who will not be saved after closing. When you open Sublime again, the files are there, like they was on close. (last session) Then you can decide to save or delete your files, when ever you want.

**Comment by dnbard** [comment]
Nice suggestions, I'll give detail comment when return from vacation. Thanks!

**Comment by dnbard** [comment]
1. Good suggestion. Will implement it.
2. Good suggestion too. Need to investigate some things prior to implementing it, but will add to the feature list.
3. Nope. This feature should not be a part of this extension. I will investigate how this can be implemented and maybe publish separate extension (no promise here).

**Comment by dnbard** [comment]
*Toggle Close-Button in Settings* is done in 1174c7ed0880e7bffb187f2bd800bf3a862904fb (v0.5.11) and will be available when Brackets Registry will be usable again.

**Comment by inovek** [comment]
Thank you!

**Comment by inovek** [comment]
Thanks again, it's working well.
While working with it, I've got a new enhancment idea, so new suggestions.

<b>Lock-feature for tabs<b>
<ul>Sometimes unintendet (middle-)clicks can be fired on/because touch-devices like the magic-mouse or touchpad surfaces. It would be really nice, to have the possibilty to lock and unlock tabs , to prevent closing.<br><br>

To toggle the lock you (the user) can simply right click the Tab and make a check-mark to the lock menu-item.</ul>

<b>Custom Colors<b>
<ul>No I don't think about a bigger color-circle, that would go beyond the scope. But in the setting for color-appeareance two text-input fields who overwrites the selection with color-hex-code would be nice.</ul>

**Comment by dnbard** [comment]
*Lock-feature for tabs*
Good idea. Will implement it with one exception: `make a check-mark to the lock menu-item`. As I know this isn't possible currently to implement using Brackets API. I will add menu-item with "Lock/Unlock" label. 

*Custom Colors*
Yep, that was an initial idea and.. I just forget to implement it =)

**Comment by inovek** [comment]
Today I realized that it isn't possible to move tabs between two documents-tooblars. (dual/split-view)
Is drag and drop between toolbars possible? Or will Brackets API don't allow that?

At the moment, I close and open files on the specific part (column/row). But I think drag and drop would be intuitive.

**Comment by dnbard** [comment]
Brackets API is very incomplete for this. For now it is possible to move documents between two panels only if receiving panel does have at least on document in it.
I know how to improve this behavior and it will be implemented in future.

**Comment by dnbard** [comment]
![2015-03-03_1411](https://cloud.githubusercontent.com/assets/4028472/6462237/167f2e70-c1b0-11e4-890e-ff20951f8403.png)
