### ISSUE TITLE
After updating icons have disappeared

### ISSUE THREAD

**Issue by DannyMoerkerke** [dnbard/brackets-documents-toolbar#50]
I have updated the extension to the latest version but now the icons now longer show up in the tabs.
Brackets version: Release 1.1 build 1.1.0-15558 (release ea908cae5) 

Settings in brackets.json:
 "dnbard.documents-toolbar.icons": true,
 "dnbard.documents-toolbar.tooltip": false,
 "dnbard.documents-toolbar.close_left": false,
 "dnbard.documents-toolbar.workingFiles": true,
 "dnbard.documents-toolbar.brackets_font": true,
 "dnbard.documents-toolbar.grayscaleIcons": false,
 "dnbard.documents-toolbar.smallIcons": false,
 "dnbard.documents-toolbar.showCloseButton": true

**Comment by dnbard** [comment]
Icons at file tabs? This extension no longer has it's own icons. Instead of this use any available extension that add file icons to working file panel.

**Comment by DannyMoerkerke** [comment]
Sorry I meant the HTML logo, JS logo etc. in the tabs which are still shown in the video.
Have they been removed or are you referring to some other icons?
Thanks.

**Comment by dnbard** [comment]
Yep, I'm talking about these icons. If you want to see them then please install appropriate icons extension: [http://brackets.dnbard.com/search/icons](http://brackets.dnbard.com/search/icons)
