### ISSUE TITLE
Ctrl+Page Up/Down to move between tabs

### ISSUE THREAD

**Issue by chylex** [dnbard/brackets-documents-toolbar#51]
Hello, I think it would be nice to have a way of moving between tabs using keyboard shortcuts instead of having to use the mouse. I'm not sure if there already is a shortcut or not, I couldn't find it though - but generally most software including IDEs and web browsers use the ones in title (Ctrl and then Page Up to go left, Page Down to go right). Thanks for considering!

**Comment by dnbard** [comment]
You already can do it with Navigation > Next/Previous document command(Ctrl-Tab / Shift-Ctrl-Tab). It's standard Brackets action (not implemented by me).

**Comment by chylex** [comment]
Right, that's really difficult to press, don't know why they went with that but at least I can rebind it. Thanks!
