### ISSUE TITLE
Change ctrl+tab action

### ISSUE THREAD

**Issue by OKNoah** [dnbard/brackets-documents-toolbar#52]
I would really like `ctrl+tab` to move to the next tab, right to left, and `shift+ctrl+tab` to move to the previous tab, left to right. This is the same way tabs are switch in, say, Safari or Chrome web browsers.

Currently this key command jumps around to different tabs because it is switching based not on position of the tab, but vertical position of the file list in the sidebar.

**Comment by dnbard** [comment]
`ctrl+tab` hotkey is set by Brackets. Extension won't change the hotkey that isn't set by Brackets itself

`vertical position of the file list in the sidebar`
It's not based on it. It will work properly when the `next document` command will use documentId for switching.
