### ISSUE TITLE
Open one file in two different tabs at the same time

### ISSUE THREAD

**Issue by djAjax** [dnbard/brackets-documents-toolbar#53]
http://joxi.ru/4Ak3z01S8KGNAq

**Comment by dnbard** [comment]
Any steps to reproduce?

**Comment by djAjax** [comment]
I have no idea, I observe this after some time, sorry.
I'll try to reproduce this, but I am not sure that I will be able...

Have a nice day.

2015-05-29 17:10 GMT+03:00 Alex Bardanov <notifications@github.com>:

> Any steps to reproduce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnbard/brackets-documents-toolbar/issues/53#issuecomment-106818344>
> .
>



-- 
CravciucAndy

**Comment by m66n** [comment]
I'm having the same problem on Linux [Brackets Release 1.4 experimental build 1.4.0-16380 (release 273804eb3)] with Documents Toolbar v0.5.17. I don't know what steps can reproduce this.

![screenshot_2015-08-05_15-20-36](https://cloud.githubusercontent.com/assets/2213892/9095586/11ca3c9e-3b86-11e5-9808-21c36d10edd5.png)

**Comment by m66n** [comment]
I think I've figured out how to make this happen. Drag the tab of a document and release the mouse button. Click on the tab to activate that document in the editor if it's not already active. Make a change in the document, and another tab for the same document appears.

**Comment by Graahf** [comment]
Having same problem, it happens for me, when I'm switching between tabs and moving them around:

http://screencast.com/t/PQ2B45Taw

**Comment by dnbard** [comment]
I want to thank everyone who are trying to pinpoint this issue. 
Unfortunately, at this point I cannot reproduce this bug to find its source.

**Comment by m66n** [comment]
I recorded a short video: https://youtu.be/KT2x_yRSOIA. I've disabled all extensions in Brackets on Linux except for Documents Toolbar. The mouse movements were not captured well, so I'll describe what I did. I doubled-clicked on 'index.html' in the side bar to open it. Then I clicked on the tab for 'index.html' and moved it slightly to the right and released the mouse button. The document disappears from the editor view, so I clicked on the tab to show it. Then I clicked to place the cursor at the end of the first line in 'index.html' and pressed the space bar. Another tab appeared. I get the same behavior on Windows 8.1.

**Comment by dnbard** [comment]
Great. Thanks to your video I've managed to reproduce this bug locally!

**Comment by dnbard** [comment]
Implemented the fix in `0.15.18`. Please test.

**Comment by Graahf** [comment]
Seems to be working, moved tabs arround, double tabbed them, only one tab appears..

Are others feeling it to? :)

**Comment by djAjax** [comment]
Good job! The issue has been fixed +1:
