### ISSUE TITLE
Unsaved documents

### ISSUE THREAD

**Issue by penafo** [dnbard/brackets-documents-toolbar#54]
Is it possible to underline, bold or change color (like Notepad++) of an unsaved file?

**Comment by dnbard** [comment]
![ ](http://content.screencast.com/users/dnbard/folders/Jing/media/77254898-3f11-4433-b016-d8389137ffc0/2015-07-01_1148.png)

**Comment by penafo** [comment]
Yup ... noticed it a bit to late :)
