### ISSUE TITLE
Seperate tab font-size from editor font size

### ISSUE THREAD

**Issue by mbaljan** [dnbard/brackets-documents-toolbar#57]
Hey, i just started working with your great extensions, but I have one serious problem with it. The font size of the text inside the tabs i somehow linked to the font size of the editor, which makes the text in the tabs ridiculous big. 

Is it possible to concern to seperate those two font-sizes from each other, so i can work with bigger fonts in the editor but have a smaller font on the tabs?

**Comment by dnbard** [comment]
It is possible. You need to do: 
* right click at the tab
* select "Show Extension Options"
* click on "General" tab
* uncheck "Use Brackets font settings"
