### ISSUE TITLE
Brackets 1.6 issue - Close button not working

### ISSUE THREAD

**Issue by djAjax** [dnbard/brackets-documents-toolbar#62]
In Brackets v.1.6 close button not working.
![screenshot_2](https://cloud.githubusercontent.com/assets/9333602/12482656/81bb6034-c059-11e5-8c66-138700108c4c.png)

**Comment by paulmz** [comment]
I had the same issue. I rolled-back Brackets to 1.5 until this is fixed. Tabs are way more important for me than any of the new Brackets features.

**Comment by hakoiko** [comment]
![image](https://cloud.githubusercontent.com/assets/7710742/12500311/45a07cf0-c0f5-11e5-93b2-655dda5d8358.png)
same issue and more here.
1.same document is opened both left&right or top&bottom panel.
2.close the document (with cmd+w). but I can't.
3.select the document on sidebar.
4.the tab has multiplied!!!
5.close the document with X button of sidebar (not both but one panel)
6.in another panel, the document is still opened. but the tab header disappeared from document toolbar both top&bottom panel.

**Comment by PatrickdeBie** [comment]
Same issue here.
Temporarily workaround: use middle mouse button (Windows, not tested on other systems)  to close tabs.

**Comment by geoffatcircle** [comment]
Same issue here! I'd love to tackle this myself if I get the time.

**Comment by GlobeTechGit** [comment]
Middle mouse button works fine in Windows 8. Thanks for the workaround.

**Comment by dnbard** [comment]
Looks like Brackets events aren't sent anymore in Brackets v1.6.0. 

I can reproduce the issue with API I'm using:
![brackets issue](https://cloud.githubusercontent.com/assets/4028472/12744640/ffbb4e02-c99d-11e5-8ac8-5dec74d17d54.gif)

FileClose event aren't updating working files list - file is still in the list event after Close menu item was selected.

**Comment by dnbard** [comment]
Also, you can hide close buttons and working files list from the options panel that is accessible from context menu:

![2016-02-02_1116](https://cloud.githubusercontent.com/assets/4028472/12744753/93a3ec32-c99e-11e5-9b44-96d874d7caf5.png)

**Comment by awojtas** [comment]
I went to Extension Options and I get the following (empty UI):

![2016-02-03 16_47_29-lftdevtheme2 css software - brackets](https://cloud.githubusercontent.com/assets/3030232/12772432/fa189bf0-ca95-11e5-9e8c-f99c89d37bbf.png)

**Comment by dinosaurfiles** [comment]
bump for this. Linux Mint 17.3, Brackets 1.6

**Comment by taniarascia** [comment]
+1 I'm using Custom Working Tabs for now.

**Comment by haizdesign** [comment]
Any news? Thanks taniarascia for the suggestion.

**Comment by charlesmigrino** [comment]
+1 Having this issue as well. So far, only middle mouse works well (Mac). Command + W (Ctrl + W) also closes the document but leaves the tab on top.

<img width="645" alt="screen shot 2016-03-10 at 10 04 04 am" src="https://cloud.githubusercontent.com/assets/17745635/13657120/b1fd7efc-e6a7-11e5-8dca-ee78b53d3d1f.png">

**Comment by edamon** [comment]
+1

**Comment by titomilton** [comment]
Thanks @PatrickdeBie for your middle mouse button suggestion.

I've tried to figured out this issue comparing the middle mouse and close button. 
Both call the function onDocumentClose in the [documents.js](../blob/master/viewmodels/documents.js#L94).
```javascript       
this.onDocumentClose = function(file){
    if (!!_.find(self.locked(), function(lockedDocumentPath){
        return lockedDocumentPath === file._path;
    })){
        return false;
    }

    CommandManager.execute('file.close', {
        file: file,
        paneId: this.panelId
    });
}
```
So, if I use the mouse middle button the `this.panelId` is `"first-pane"`,
but for close button it's `undefined`.
Therefore, when this snippet is changed as below, the close button have the same middle mouse button behaviour.
```javascript
CommandManager.execute('file.close', {
    file: file,
    paneId: this.panelId || 'first-pane'
});
```
I think it seems more a workaround than a solution and must be better understand where `this.panelId` is changed. And it's not resolve the problem with Command + W (Ctrl + W).

**Comment by titomilton** [comment]
Actually, the correction must be to use `self.panelId` instead of `this.panelId`:
```javascript
CommandManager.execute('file.close', {
    file: file,
    paneId: self.panelId
});
```
But the Command + W (Ctrl + W) persists. Should do I pull request it and open another issue regarding the close shortcut or try to fix it and pull request both?
