### ISSUE TITLE
Keyboard shortcut to switch tabs is reversed

### ISSUE THREAD

**Issue by petervangalen** [dnbard/brackets-documents-toolbar#66]
When I have three tabs open, Command+Shift+[ goes to the tab on the right and Command+Shift+] goes to the tab on the left. That's opposite of what it's supposed to be, right? I had the same issue with another tab extension...I fixed it with reversing the shortcuts in preferences.

**Comment by dnbard** [comment]
This shortcut are controlled by Brackets editor itself. Not the extension.
