### ISSUE TITLE
Plugin Breaks when using it alongside Brackets Git

### ISSUE THREAD

**Issue by Xandernardo** [dnbard/brackets-documents-toolbar#67]
It's a really useful plugin, but recently I needed Git support for my project and Git Brackets makes git usage a breeze, so I installed it, just to find it break completly this plugin.

I'm not sure if I should report this to the Brackets Git plugin place or here, so I started here.

Thanks a lot for this useful plugin, I hope I can get both working together flawlessly in the future.

**Comment by dnbard** [comment]
I'm using brackets-documents-toolbar with brackets-git since the day one and don't have any problems. It's really unlikely that these 2 plugins will have integration issues.
Please post errors from Brackets Development Tools (F12) here to investigate.

**Comment by Xandernardo** [comment]
I feel embarrassed, all I had to do was double-clicking the file to open it in the half-window I wanted. I got used to 1-click = show in the corresponding bar, and took that as a bug.

I'm sorry for the trouble this could have caused. In any case I will post here the errors, but for what I got from the code they are mostly emmet related and have nothing to do with git or documents-toolbar.

```
PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:548:24)
2/command/Menus.js:820 Error setting menu item shortcut: 1
/command/CommandManager.js:195 Attempting to register an already-registered command: dt.reopenDocument
/command/KeyBindingManager.js:857 addBinding(): missing required parameter: command
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-T to io.emmet.matching_pair. It is already assigned to dt.reopenDocument
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
/command/Menus.js:820 Error setting menu item shortcut: 1
```

**Comment by dnbard** [comment]
No problem.

> all I had to do was double-clicking the file to open it in the half-window I wanted.

This extension tries to use Brackets functionality by maximum and tabs created only when file are added to working list of files. This is done only on double-click by Brackets itself.
